{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "rackspace-spot-exporter.fullname" . }}
  labels:
    {{- include "rackspace-spot-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rackspace-spot-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    path: {{ .Values.exporter.metricsPath }}
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
{{- end }}
