{{- if not .Values.rackspaceSpot.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rackspace-spot-exporter.fullname" . }}
  labels:
    {{- include "rackspace-spot-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  refresh-token: {{ .Values.rackspaceSpot.refreshToken | required "rackspaceSpot.refreshToken is required when existingSecret is not set" | quote }}
{{- end }}
